site_name: Le C pour l'ingénieur
site_url: https://example.com/
nav:
  - Section:
    - Home: index.md
    - Listings: listings.md
  - Notebook page: notebook.ipynb
  - Python file: python_script.py
  - Tags: tags.md
watch:
  - includes
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.view
  language: fr
  logo: assets/heig-vd-white.svg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: red
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    view: material/eye
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra:
  homepage: https://example.com
  annotate:
    json: [.s2]
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heig-tin-info/handbook
  generator: false
plugins:
  - mkdocs-jupyter
  - glightbox
  - info
  - charts
  - git-revision-date-localized:
      enable_creation_date: true
  - tags:
      listings_toc: true
      tags_file: tags.md
      tags_hierarchy: true
  - drawio-exporter
  - toggle-sidebar
  - markdown-exec
  - extract_listings:
      listings_file: listings.md
      placeholder: PLACEHOLDER_LISTINGS_PLUGIN
  - enumerate-headings:
      toc_depth: 0
      increment_across_pages: true
  - search
markdown_extensions:
  - toc:
      toc_depth: 3
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.blocks.admonition
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
copyright: Copyright &copy; 2019 - 2024 HEIG-VD Yves Chevallier
repo_url: https://github.com/heig-tin-info/handbook