# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: L'informatique pour ingénieurs
site_url: https://heig-tin-info.github.io/handbook/
site_author: Yves Chevallier
site_description: |
  Cours d'informatique pour les étudiants en ingénierie du département des
  technologies industrielles à la HEIG-VD. Ce cours concerne le langage C et
  les outils associés.
copyright: >
  Copyright &copy; 2019 - 2024 HEIG-VD Yves Chevallier -
  <a href="#__consent">Paramètres des cookies</a>

# Repository information
repo_name: heig-tin-info/handbook
repo_url: https://github.com/heig-tin-info/handbook
edit_uri: edit/master/docs/
docs_dir: !ENV [DOCS, docs]
validation:
  absolute_links: relative_to_docs
theme:
  name: material
  language: fr
  custom_dir: overrides
  font:
    text: Nunito
  logo: https://raw.githubusercontent.com/HEIG-VD/logos/main/heig-vd/heig-vd-white.svg
  favicon: assets/icons/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips # [Insiders only]
    - header.autohide
    - navigation.footer # Adds previous and next buttons in the footer
    - navigation.instant # Dispatch through XHR, without full page reload
    - navigation.instant.preview # [Insiders only]
    - navigation.instant.prefetch # [Insiders only]
    - navigation.instant.progress # [Insiders only]
    - navigation.path # [Insiders only]
    - navigation.indexes # Allows for entry pages for each section
    - navigation.tabs # Render top-level section in navbar
    - navigation.top # Adds back-to-top button
    - navigation.tracking # Update address bar with current page
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: red
      accent: light blue
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/goal-16
      tip: octicons/light-bulb-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      exercise: octicons/mortar-board-16
      solution: octicons/trophy-16
      hint: octicons/light-bulb-16
      foobar: octicons/check-circle-16
      failure: octicons/x-circle-16
      reload: octicons/sync-16
plugins:
  - group:
      enabled: !ENV CI
      plugins:
        #- privacy # Seem to mess with images
        # - mike
        # - minify:
        #     minify_html: true # Break draw.io images?
        - git-committers:
            repository: heig-tin-info/handbook
            branch: master
        - optimize
        - git-revision-date-localized:
            enable_creation_date: true
        - git-authors
  - autorefs:
      resolve_closest: true
  - caption:
      figure:
        reference_text: ''
        caption_prefix: ''
        ignore_classes: [nocaption]
      table:
        reference_text: ''
        caption_prefix: ''
        position: top
  # - social # Not supporting external logo link
  - awesome-pages
  - tags
  - epigraph
  - pills
  - glightbox:
      skip_classes:
        - drawio-diagram
  - markdown-exec
  - search
  - exercises
exclude_docs: README.md
markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: "¤"
      permalink_title: Lien permanent
  - pymdownx.betterem:
      smart_enable: all
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.blocks.admonition
  - pymdownx.blocks.html
  - pymdownx.magiclink
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      check_paths: true
      url_max_size: 2048
      url_timeout: 3
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  latex:
    enabled: true
    build_dir: build
    mermaid_config: tex/mermaid-config.json
    clean_assets: false

    books:
      - root: Cours C
        cover:
          name: circles
          color: indigo(dye)
          logo: c-logo.pdf
        title: L'informatique pour l'ingénieur
        subtitle: Cours de programmation en C
        folder: book
        save_html: true
        email: yves.chevallier@heig-vd.ch
        index_is_foreword: true
        drop_title_index: true
        frontmatter:
          - Préface
        backmatter:
          - colophon
        copy_files:
          docs/assets/c-logo.pdf: assets/
          tex/*.sty: .
          tex/*.tex: .
      - root: Outils
        cover:
          name: circles
          color: PineGreen
          logo: tool-hero.pdf
        base_level: -1
        title: Outils de développement
        subtitle: Aux utilisateurs de Git, GCC, Make, Python...
        folder: tools
        save_html: true
        email: yves.chevallier@heig-vd.ch
        copy_files:
          tex/tool-hero.pdf: assets/
          tex/*.sty: .
          tex/*.tex: .
  admonition_translations:
    tip: Astuce
    warning: Avertissement
    example: Exemple
    cite: Citation
    bug: Bogue
    exercise: Exercice

  consent:
    title: Cookie consent
    description: >-
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos préférences,
      ainsi que pour mesurer l'efficacité de notre documentation et savoir si les
      utilisateurs trouvent ce qu'ils recherchent. Avec votre consentement,
      vous nous aidez à améliorer notre documentation.

  analytics:
    provider: google
    property: G-FVF0WYPMYM
    feedback:
      title: ""
      ratings:
        - icon: material/emoticon-happy-outline
          name: Cette page m'a été utile
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Cette page pourrait être améliorée
          data: 0
          note: >-
            Merci pour votre retour !
  homepage: https://heig-tin-info.github.io/handbook
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heig-tin-info/handbook
watch:
  - includes
  - overrides
hooks:
  - hooks/index.py # Index keywords in codes (language)
  - hooks/drawio.py # Embedded draw.io diagrams
  - hooks/spantable.py # Adds span table support
  - hooks/french.py # French typography
  - hooks/wiki.py # Wiki tips on hover
  - hooks/latex.py # LaTeX conversion
  - hooks/tags.py # Custom tags
  - hooks/mermaid.py # Support for captions in mermaid diagrams
  - hooks/abbr.py # Abbreviations to Wiki links
extra_css:
  - css/french.css
  - css/extra.css
  - css/tables.css
  - css/drawio.css
extra_javascript:
  - js/viewer.min.js  # https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/viewer.min.js
  - js/drawio.js
  - js/wiki-tips.js
  - js/feedback.js
  - js/mathjax.js
  - js/navcolor.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
