# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: Le C pour l'ingénieur
site_url: https://heig-tin-info.github.io/handbook/
site_author: Yves Chevallier
site_description: |
  Un manuel pour apprendre le langage C en partant de zéro.
copyright: Copyright &copy; 2019 - 2024 HEIG-VD Yves Chevallier

# Repository information
repo_name: heig-tin-info/handbook
repo_url: https://github.com/heig-tin-info/handbook
edit_uri: edit/master/docs/
docs_dir: docs

theme:
  name: material
  language: fr
  custom_dir: overrides
  font:
    text: Segoe UI
    code: Consolas
  logo: assets/logos/heig-vd-white.svg
  favicon: assets/icons/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.footnote.tooltips # [Insiders only]
    - header.autohide
    - navigation.footer # Adds previous and next buttons in the footer
    - navigation.instant # Dispatch through XHR, without full page reload
    - navigation.instant.preview # [Insiders only]
    - navigation.instant.prefetch # [Insiders only]
    - navigation.instant.progress # [Insiders only]
    - navigation.path # [Insiders only]
    #- navigation.expand
    #- navigation.sections # Render top-level section as groups
    - navigation.indexes # Allows for entry pages for each section
    #- navigation.prune
    - navigation.tabs # Render top-level section in navbar
    - navigation.top # Adds back-to-top button
    - navigation.tracking # Update address bar with current page
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      #media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: red
      accent: light blue
    - scheme: slate
      #media: "(prefers-color-scheme: dark)"
      primary: red
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/goal-16
      tip: octicons/light-bulb-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      exercise: octicons/mortar-board-16
      solution: octicons/trophy-16
      hint: octicons/light-bulb-16
      foobar: octicons/check-circle-16
      failure: octicons/x-circle-16
      reload: octicons/sync-16
plugins:
  - group:
      enabled: !ENV CI
      plugins:
        #- privacy # Seem to mess with images
        # - mike
        #- info
        # - minify:
        #     minify_html: true # Break draw.io images?
        - git-committers:
            repository: heig-tin-info/handbook
            branch: master
            token: !ENV ["GH_TOKEN"]
        - optimize
        - git-revision-date-localized:
            enable_creation_date: true
        - git-authors
  - caption
  - charts
  - autorefs
  #- toggle-sidebar  # Seems buggy
  - awesome-pages

  # - i18n:
  #     languages:
  #       - locale: fr
  #         default: true
  #         name: Français
  #         admonition_translations:
  #           tip: Astuce
  #           warning: Avertissement

  - tags
  # - drawio-exporter:
  #     cache_dir: .drawio_cache
  #     embed_format: '{content}'
  - glightbox:
      skip_classes:
        - drawio-diagram
  - markdown-exec
  # - extract_listings:
  #     listings_file: listings.md
  #     placeholder: PLACEHOLDER_LISTINGS_PLUGIN
  # - enumerate-headings:
  #     toc_depth: 3
  #     increment_across_pages: true
  #     exclude:
  #       - index.md
  - search
  #- htmlproofer  # Very slow, and not accurate

  #- exercises
markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.blocks.admonition
  - pymdownx.blocks.html
  - pymdownx.magiclink
  - admonition
  - footnotes
  - material.extensions.preview
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      check_paths: true
      url_max_size: 2048
      url_timeout: 3
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  admonition_translations:
    tip: Astuce
    warning: Avertissement
    example: Exemple
    cite: Citation
    bug: Bogue
  tags:
    foo: Bob
    bar: Alice
    baz: Eve
  analytics:
    provider: google
    property: G-FVF0WYPMYM
    feedback:
      title: Cette page vous a-t-elle été utile ?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Cette page m'a été utile
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Cette page pourrait être améliorée
          data: 0
          note: >-
            Merci pour votre retour !
  homepage: https://heig-tin-info.github.io/handbook
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heig-tin-info/handbook
watch:
  - includes
  - overrides
hooks:
  - hooks/drawio.py
  - hooks/links.py
  - hooks/unicode.py
  - hooks/spantable.py
  - hooks/regex.py
  - hooks/french.py
  - hooks/wiki.py
  - hooks/latex.py
extra_css:
  - css/french.css
  - css/callout.css
  - css/extra.css
  - css/tables.css
extra_javascript:
  - js/viewer.min.js
  - js/drawio.js
  - js/wiki-tips.js
  - js/feedback.js
  - js/mathjax.js
  #- js/tablesort.js
  #- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # Unwanted for certain tables
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
