# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: Le C pour l'ingénieur
site_url: https://example.com/
site_author: Yves Chevallier
site_description: |
  Un manuel pour apprendre le langage C en partant de zéro.
copyright: Copyright &copy; 2019 - 2024 HEIG-VD Yves Chevallier

# Repository information
repo_name: heig-tin-info/handbook
repo_url: https://github.com/heig-tin-info/handbook

watch:
  - includes
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  #custom_dir: overrides
  features:
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    #- instant
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: fr
  logo: assets/heig-vd-white.svg
  favicon: assets/favicon.ico
  font:
    text: Segoe UI
    code: Consolas
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: red
      accent: light blue
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: red
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    view: material/eye
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      exercise: octicons/mortar-board-16
      solution: octicons/light-bulb-16
extra:
  homepage: https://example.com
  annotate:
    json: [.s2]
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heig-tin-info/handbook
  generator: false
plugins:
  #- mkdocs-jupyter
  - glightbox
  - info
  - caption
  - charts
  - autorefs
  - awesome-pages
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - tags:
      tags_file: tags.md
  - drawio-exporter
  - markdown-exec
  - extract_listings:
      listings_file: listings.md
      placeholder: PLACEHOLDER_LISTINGS_PLUGIN
  - enumerate-headings:
      toc_depth: 0
      increment_across_pages: true
  - search
  - minify:
      minify_html: true
markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.blocks.admonition
  - pymdownx.blocks.html
  - pymdownx.magiclink
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - javascripts/multiple-choice.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
